Asp.net Practice/Areas/Kudvenkat/Models/Empolyee/Empolyee.cs
using System.ComponentModel.DataAnnotations;

namespace Asp.net_Practice.Areas.Kudvenkat.Models.Empolyee
{
    public class Empolyee
    {
        [Required]
        public int Id { get; set; }
        [Required]
        [MaxLength(50)]
        public string? Name { get; set; }
        [Required]
        public string? Address { get; set; }
        public EnumEmpolyee  Department { get; set; }
    }
}

Asp.net Practice/Areas/Kudvenkat/Models/Empolyee/EnumEmpolyee.cs
namespace Asp.net_Practice.Areas.Kudvenkat.Models.Empolyee
{
    public enum EnumEmpolyee
    {
        BiomedicalEngineering,
        Bangla,
        English,
        Finance,
        Potitical_science,
        EEE,
        CSE,
        BTGE,
        Turism,
        ICT

    }
}

Asp.net Practice/Areas/Kudvenkat/Models/Empolyee/IReposity/IEmpolyee.cs
namespace Asp.net_Practice.Areas.Kudvenkat.Models.Empolyee
{
    public interface IEmpolyee
    {

        Empolyee get(int id);
        List<Empolyee> getList();
        Empolyee Add(Empolyee empolyee);
        Empolyee Upadate(Empolyee empolyee);
        Empolyee Delete(int id);
    }
}

Asp.net Practice/Areas/Kudvenkat/Models/Empolyee/RepositoryClass/EmpolyeeRepository.cs
using Asp.net_Practice.Areas.Kudvenkat.Models.Empolyee;
namespace Asp.net_Practice.Areas.Kudvenkat.Models.Empolyee.RepositoryClass
{
    public class EmpolyeeRepository : IEmpolyee
    {

        List<Empolyee> empolyees = new List<Empolyee>()
        {
            new Empolyee(){Id=1,Name="Sojib",Address="Pabna",Department=EnumEmpolyee.EEE},
            new Empolyee(){Id=2,Name="Abir",Address="Dhaka",Department=EnumEmpolyee.Finance},
            new Empolyee(){Id=3,Name="Kabir",Address="Jamalpur",Department=EnumEmpolyee.Potitical_science},
            new Empolyee(){Id=4,Name="Shakhawat",Address="Karimabad",Department=EnumEmpolyee.Bangla},
            new Empolyee(){Id=5,Name="Shariar",Address="India",Department=EnumEmpolyee.BiomedicalEngineering},
            new Empolyee(){Id=6,Name="Rabiul",Address="Khulna",Department=EnumEmpolyee.BTGE},
            new Empolyee(){Id=7,Name="Shopon",Address="Bogura",Department=EnumEmpolyee.Finance}
        };

        public Empolyee Add(Empolyee empolyee)
        {
            empolyees.Add(empolyee);
            return empolyee;
        }

        public Empolyee Delete(int id)
        {
            var emp =empolyees.Where(e => e.Id == id).FirstOrDefault();
            if(emp!=null)
            {
                empolyees.Remove(emp);
            }
            return emp;
        }

        public Empolyee get(int id)
        {
            return empolyees.Where(e => e.Id == id).FirstOrDefault();

        }

        public List<Empolyee> getList()
        {
            return empolyees;
        }

        public Empolyee Upadate(Empolyee empolyee)
        {
            var emp=empolyees.Where(e => e.Id == empolyee.Id).FirstOrDefault();
            emp.Name = empolyee.Name;
            emp.Address = empolyee.Address;
            emp.Id = empolyee.Id;
            emp.Department = empolyee.Department;


            return emp;
        }
    }
}

Asp.net Practice/Areas/Kudvenkat/Models/Empolyee/RepositoryClass/SqlServerRepository.cs
using Asp.net_Practice.Areas.Kudvenkat.Models.Empolyee.contex;

namespace Asp.net_Practice.Areas.Kudvenkat.Models.Empolyee.RepositoryClass
{
    public class SqlServerRepository : IEmpolyee
    {
        private readonly EmpolyeeContecxt _context;
        public SqlServerRepository(EmpolyeeContecxt context)
        {
            _context = context;
        }
        public Empolyee Add(Empolyee empolyee)
        {
            _context.empolyees.Add(empolyee);
            _context.SaveChanges();
            return empolyee;
        }

        public Empolyee Delete(int id)
        {
            Empolyee? emp = _context.empolyees.Find(id);
            if (emp != null)
            {
                _context.empolyees.Remove(emp);
                _context.SaveChanges();
            }
            return emp;

        }

        public Empolyee get(int id)
        {
             Empolyee emp= _context.empolyees.Find(id);
            return emp;
        }

        public List<Empolyee> getList()
        {
            return _context.empolyees.ToList();
        }

        public Empolyee Upadate(Empolyee empolyee)
        {
           var emp= _context.empolyees.Attach(empolyee);
           emp.State=Microsoft.EntityFrameworkCore.EntityState.Modified;
            _context.SaveChanges();
            return empolyee;

        }
    }
}

Asp.net Practice/Models/ErrorViewModel.cs
namespace Asp.net_Practice.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Asp.net Practice/Areas/Kudvenkat/Controllers/KudController.cs
using Asp.net_Practice.Areas.Kudvenkat.Models.Empolyee;
using Asp.net_Practice.Areas.Kudvenkat.Models.Empolyee.RepositoryClass;
using Microsoft.AspNetCore.Mvc;

namespace Asp.net_Practice.Areas.Kudvenkat.Controllers
{
    [Area("Kudvenkat")]
    public class KudController : Controller
    {
        private readonly IEmpolyee _empolyee;

        public KudController(IEmpolyee empolyee)
        {
            _empolyee = empolyee;
        }
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult GetEmpolyee(int id)
        {
            var result = _empolyee.get(id);
            return View(result);
        }
        public IActionResult ListofEmpolyee()
        {
            var result = _empolyee.getList();
            return View(result);
        }
        [HttpGet]
        public IActionResult CreateForm()
        {
            return View();
        }
        [HttpPost]
        public IActionResult CreateForm(Empolyee empolyee)
        {

            if(ModelState.IsValid)
            {
               Empolyee emp= _empolyee.Add(empolyee);
                return RedirectToAction("GetEmpolyee", new {id=emp.Id});
            }
            else
            {
                ViewBag.Invalid = "Form can't create Successfully";
                return View();
            }
            
            
            
        }
    }
}

Asp.net Practice/Controllers/HomeController.cs
using Asp.net_Practice.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace Asp.net_Practice.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Asp.net Practice/Areas/Kudvenkat/Views/Kud/CreateForm.cshtml
@model Empolyee 
@{
    ViewData["Title"] = "CreateForm";
}

<div>
    @ViewBag.Valid
</div>
<div>
    @ViewBag.Invalid
</div>
<div class="container">
    <div class="row">
        <div class="col-md-6 grid-margin stretch-card">
            <div class="card">
                <div class="card-body">
                    <h4 class="card-title">Default form</h4>
                    <p class="card-description">
                        Basic form layout
                    </p>
                    <form asp-controller="Kud" asp-action="CreateForm" method="post" class="forms-sample">
                        <div class="form-group">
                            <label asp-for="Id"></label>
                            <input asp-for="Id" class="form-control" id="exampleInputUsername1" placeholder="UserId">
                            <span asp-validation-for="Id" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="Name"></label>
                            <input asp-for="Name" class="form-control" id="exampleInputEmail1" placeholder="Name">
                            <span asp-validation-for="Name" class=" text-danger"></span> 
                        </div>
                        <div class="form-group">
                            <label asp-for="Address"></label>
                            <input asp-for="Address" class="form-control" id="exampleInputPassword1" placeholder="Address">
                            <span asp-validation-for="Address" class=" text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="Department"></label>
                            <select asp-for="Department"  asp-items="Html.GetEnumSelectList<EnumEmpolyee>()"
                              class="form-control" id="exampleInputConfirmPassword1"> </select>
                        </div>
                        <button type="submit" class="btn btn-primary mr-2">Submit</button>
                        <button class="btn btn-light">Cancel</button>
                    </form>
                </div>
            </div>
        </div>
</div>
</div>

Asp.net Practice/Areas/Kudvenkat/Views/Kud/GetEmpolyee.cshtml
@model Empolyee
@{
    ViewData["Title"] = "GetEmpolyee";
}
@section Style
{
    <Link  rel="stylesheet" href="~/css/site.css"/>
}

<div class="card" style="width:400px">
  <img class="card-img-top" src="~/Kudvenkat/images/img_avatar1.png" alt="Card image">
  <div class="card-body">
    <h4 class="card-title">@Model.Name</h4>
    <p class="card-text">@Model.Address</p>
    <a  asp-controller="Kud" asp-action="ListofEmpolyee" class="btn btn-primary">Back</a>
    <a href="#" class="btn btn-primary">Edit</a>
  </div>
</div>

Asp.net Practice/Areas/Kudvenkat/Views/Kud/Index.cshtml
@{
    ViewData["Title"] = "Index";
}

<a asp-controller="Kud" asp-action="CreateForm" class="btn-green">Create Form</a>

Asp.net Practice/Areas/Kudvenkat/Views/Kud/ListofEmpolyee.cshtml
@model List<Empolyee> 

@{
    ViewData["Title"] = "ListofEmpolyee";
}

@section Style
{
    <link href="h:\software engineering\devskill-asp.net mvc\practice\practice\asp.net practice\wwwroot\css\site.css" rel="stylesheet" />
}

    <div class="conatainer">
        <div class="row">
        @foreach(var item in Model)
        {
            <div class="col-lg-4">
                <div class="card" style="width:400px">
                    <img class="card-img-top" src="~/Kudvenkat/images/img_avatar1.png" alt="Card image">
                    <div class="card-body">
                        <h4 class="card-title">@item.Name</h4>
                        <p class="card-text">@item.Department</p>
                        <a asp-controller="Kud" asp-action="GetEmpolyee" asp-route-id="@item.Id" class="btn btn-primary">See Profile</a>
                        <a href="#" class="btn btn-primary">Back</a>
                    </div>
                </div>
            </div>
    
        }
    </div>

</div>

Asp.net Practice/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Asp.net Practice/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Asp.net_Practice</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Asp.net_Practice.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Asp.net_Practice</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Asp.net_Practice - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>